import {useEffect,useState} from 'react'
import {m3Api,type Investigation,type Source,type User} from '../../api/m3'
import {IntelligencePanel} from '../m5/IntelligencePanel'

const accounts=[['Investigator','investigator.demo'],['Crime Analyst','analyst.demo'],['Supervisor','supervisor.demo']] as const
const examples=['Find unresolved chain snatching at SYN-STN-01','ಬಗೆಹರಿಯದ ಸರಗಳ್ಳತನ ಜಯನಗರ ತೋರಿಸಿ','Last three months alli Jayanagar hatra similar unresolved chain-snatching cases show maadi.']

export function InvestigationExperience(){
 const [user,setUser]=useState<User|null>(null),[password,setPassword]=useState(''),[username,setUsername]=useState('investigator.demo'),[home,setHome]=useState<any>(null),[inv,setInv]=useState<Investigation|null>(null),[control,setControl]=useState<any>(null),[selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState(''),[follow,setFollow]=useState(''),[preview,setPreview]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[results,setResults]=useState<any[]>([]),[detail,setDetail]=useState<any>(null),[passport,setPassport]=useState<any>(null),[path,setPath]=useState<any>(null),[busy,setBusy]=useState(''),[error,setError]=useState('')
 const call=async(label:string,fn:()=>Promise<any>)=>{setBusy(label);setError('');try{return await fn()}catch(e){setError((e as Error).message);return null}finally{setBusy('')}}
 const load=async()=>{const h=await m3Api.home();setHome(h);const c=await m3Api.sourceControl('Active Case Investigation');setControl(c)}
 async function login(){const u=await call('login',()=>m3Api.login(username,password));if(u){setUser(u);await load()}}
 async function open(i:Investigation){setInv(i);setSelected(i.selected_sources);setHistory(await m3Api.history(i.id));setControl(await m3Api.sourceControl(i.purpose))}
 async function create(){const next=await call('create',()=>m3Api.createInvestigation({title:'M4 synthetic investigation',purpose:user?.role==='CRIME_ANALYST'?'Pattern Research':'Active Case Investigation',selected_sources:selected.length?selected:['CCTNS_REPLICA']}));if(next){await open(next);await load()}}
 async function preset(name:string){if(!inv)return;const next=await call('preset',()=>m3Api.preset(inv.id,name));if(next){setInv(next);setSelected(next.selected_sources)}}
 async function saveSources(){if(!inv)return;const next=await call('sources',()=>m3Api.updateSources(inv.id,selected));if(next)setInv(next)}
 async function doPreview(text=query, parent?:string){if(!inv)return;const value=await call('preview',()=>parent?m3Api.followUp(inv.id,parent,text):m3Api.preview(inv.id,text));if(value){setPreview(value);setHistory(await m3Api.history(inv.id))}}
 async function run(){if(!inv||!preview)return;const plan=preview.normalised_interpretation;const data=await call(plan.intent==='DISCOVER'?'discover':'search',()=>plan.intent==='DISCOVER'?m3Api.discover(inv.id,plan):m3Api.search(inv.id,plan));if(data)setResults(data.results||[])}
 if(!user)return <section className="mt-8 rounded-2xl border bg-white p-7 shadow-panel"><h2 className="text-2xl font-semibold">Demo Login</h2><p className="mt-1 text-sm text-slate-600">Synthetic role accounts; server-side policy controls every factual response.</p><div className="mt-4 flex gap-2">{accounts.map(([name,value])=><button key={value} onClick={()=>setUsername(value)} className="rounded border px-3 py-2">{name}</button>)}</div><label className="mt-3 block">Demo password<input aria-label="Demo password" className="ml-2 rounded border p-2" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="mt-3 rounded bg-navy-800 px-4 py-2 text-white" onClick={()=>void login()}>{busy==='login'?'Signing in…':'Login'}</button>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}</section>
 return <section className="mt-8 grid gap-5" aria-label="Investigation Home"><header className="rounded-2xl bg-navy-950 p-6 text-white"><div className="flex justify-between"><div><p className="text-xs text-teal-300">{user.role}</p><h2 className="text-2xl font-semibold">Investigation Home</h2><p className="text-sm">{user.assigned_station||'Pattern scope'} · {user.assigned_district}</p></div><button onClick={()=>void m3Api.logout().then(()=>setUser(null))}>Logout</button></div>{home?.degraded_mode&&<p className="mt-3 rounded bg-amber-200 p-2 text-sm text-amber-950">Degraded mode: {home.degraded_sources.join(', ')}. Results remain limited to authorised available sources.</p>}</header>
 {!inv?<div className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Recent investigations</h3>{home?.recent_investigations?.map((x:Investigation)=><button key={x.id} className="m-2 rounded border p-3 text-left" onClick={()=>void open(x)}>{x.title}<br/><small>{x.selected_sources.join(', ')}</small></button>)}<div className="mt-4"><h3 className="font-semibold">Create investigation</h3><div className="mt-2 flex flex-wrap gap-2">{control?.sources?.filter((s:Source)=>s.selectable).map((s:Source)=><label key={s.id} className="rounded border p-2"><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id))}/>{s.name} · {s.status}</label>)}</div><button className="mt-3 rounded bg-teal-600 px-4 py-2 text-white" onClick={()=>void create()}>Create investigation</button></div></div>:
 <><section className="rounded-2xl border bg-white p-6"><div className="flex justify-between"><div><p className="text-xs text-teal-600">{inv.purpose}</p><h3 className="text-xl font-semibold">{inv.title}</h3></div><button onClick={()=>setInv(null)}>Back to home</button></div><h4 className="mt-4 font-semibold">Source Control Centre</h4><div className="mt-2 flex flex-wrap gap-2">{Object.keys(control?.presets||{}).map(p=><button className="rounded border px-2 py-1" key={p} onClick={()=>void preset(p)}>{p}</button>)}</div><div className="mt-3 grid gap-2 md:grid-cols-2">{control?.sources?.map((s:Source & any)=><label key={s.id} className="rounded border p-3 text-sm"><input type="checkbox" disabled={!s.selectable} checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id))}/><b className="ml-2">{s.name}</b><p>{s.status} · {s.reliability_role}</p><small>{s.limitation}</small></label>)}</div><button className="mt-3 rounded bg-navy-800 px-3 py-2 text-white" onClick={()=>void saveSources()}>Save source selection</button></section>
 <section className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Investigation Workspace</h3><p className="mt-1 text-xs text-slate-500">Examples: {examples.map(x=><button className="ml-2 underline" key={x} onClick={()=>setQuery(x)}>{x}</button>)}</p><textarea aria-label="Multilingual query" className="mt-3 min-h-24 w-full rounded border p-3" value={query} onChange={e=>setQuery(e.target.value)} placeholder="English, ಕನ್ನಡ, or Kannada-English code-mixed query"/><button className="mt-2 rounded bg-navy-800 px-3 py-2 text-white" onClick={()=>void doPreview()}>Preview query</button>{history.length>0&&<div className="mt-3 text-sm"><b>Query history</b>{history.map(h=><button className="ml-2 rounded border px-2" key={h.id} onClick={()=>setFollow(h.id)}>{h.original_text.slice(0,32)}</button>)}</div>}<textarea aria-label="Follow-up query" className="mt-3 w-full rounded border p-2" value={follow} onChange={e=>setFollow(e.target.value)} placeholder="Follow-up: Phone, IMEI athava vehicle connection iruva cases matra."/><button className="mt-2 rounded border px-3 py-2" disabled={!history.length} onClick={()=>void doPreview(follow,history.at(-1)?.id)}>Preview follow-up</button></section>
 {preview&&<section className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Editable Query Preview</h3><p className="text-sm">Intent: <b>{preview.normalised_interpretation?.intent}</b> {preview.inherited_fields&&`· inherited: ${preview.inherited_fields.join(', ')}`}</p>{preview.normalised_interpretation?.requires_confirmation&&<p className="text-amber-700">Confirmation required: {preview.normalised_interpretation.uncertain_fields.join(', ')}</p>}<button className="mt-3 rounded bg-teal-600 px-3 py-2 text-white" onClick={()=>void run()}>Confirm and run {preview.normalised_interpretation?.intent}</button></section>}
 <section className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Results</h3>{results.length===0?<p className="text-sm text-slate-500">No results yet. Results appear before interpretation.</p>:results.map(r=><article key={r.id} className="mt-3 rounded border p-3"><b>{r.fir_number}</b> · {r.offence} · {r.status}<p className="text-sm">{r.relationship_reason||r.match_reasons?.join(', ')} · {r.jurisdiction_state} · {r.masking?.applied?'Masked':'Full permitted'}</p><p className="text-xs">Sources: {(r.source_record_references||[]).join(', ')}</p><button className="mr-2 underline" onClick={()=>void call('case',()=>m3Api.case360(r.id)).then(setDetail)}>Open Case 360</button><button className="underline" onClick={()=>void call('passport',()=>m3Api.passport(r.source_record_references?.[0])).then(setPassport)}>Open Source Passport</button></article>)}</section>
 {detail&&<section className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Case 360</h3>{['overview','entities','evidence','timeline','source_records','trust_issues'].map(tab=><details className="mt-2" key={tab}><summary className="capitalize">{tab.replaceAll('_',' ')}</summary><pre className="overflow-auto text-xs">{JSON.stringify(detail[tab],null,2)}</pre></details>)}<button onClick={()=>void call('path',()=>m3Api.path(detail.overview.id,detail.entities?.[0]?.id)).then(setPath)}>Show bounded relationship path</button>{path&&<pre className="mt-2 text-xs">{JSON.stringify(path,null,2)}</pre>}</section>}
 {passport&&<section className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Source Passport</h3><pre className="overflow-auto text-xs">{JSON.stringify(passport,null,2)}</pre></section>}</>}{error&&<p role="alert" className="text-red-700">{error}</p>}</section>
 {detail&&<IntelligencePanel caseId={detail.overview.id}/>} 
}
