import {useState} from 'react'
import {m3Api,type Investigation,type Source,type User} from '../../api/m3'

const accounts=[['Investigator','investigator.demo'],['Crime Analyst','analyst.demo'],['Supervisor','supervisor.demo']] as const
const purposes=['Active Case Investigation','Entity Verification','Pattern Research','Supervisor Review','Procedural Review']

export function AuthQueryWorkspace(){
 const [user,setUser]=useState<User|null>(null),[username,setUsername]=useState('investigator.demo'),[password,setPassword]=useState(''),[error,setError]=useState(''),[sources,setSources]=useState<Source[]>([]),[selected,setSelected]=useState<string[]>([]),[title,setTitle]=useState('Synthetic investigation'),[purpose,setPurpose]=useState('Active Case Investigation'),[investigation,setInvestigation]=useState<Investigation|null>(null),[query,setQuery]=useState(''),[preview,setPreview]=useState<any>(null),[results,setResults]=useState<any[]>([]),[busy,setBusy]=useState('')
 async function login(){setBusy('login');setError('');try{const u=await m3Api.login(username,password);setUser(u);const s=await m3Api.sources();setSources(s);setSelected(s.filter(x=>x.selectable).slice(0,3).map(x=>x.id));if(u.role==='SUPERVISOR')setPurpose('Supervisor Review');else if(u.role==='CRIME_ANALYST')setPurpose('Pattern Research')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function logout(){await m3Api.logout();setUser(null);setInvestigation(null);setPreview(null);setResults([])}
 async function create(){setBusy('create');setError('');try{setInvestigation(await m3Api.createInvestigation({title,purpose,selected_sources:selected}))}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function parse(){if(!investigation)return;setBusy('preview');setError('');try{setPreview(await m3Api.preview(investigation.id,query))}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function run(){if(!investigation||!preview)return;setBusy('search');setError('');try{const data=await m3Api.search(investigation.id,preview.normalised_interpretation);setResults(data.results)}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 if(!user)return <section className="mt-8 rounded-2xl border bg-white p-7 shadow-panel" aria-labelledby="demo-login"><h2 id="demo-login" className="text-2xl font-semibold">Demo Login</h2><p className="mt-2 text-sm text-slate-600">Synthetic roles only. Credentials are configured locally and never represent real users.</p><div className="mt-4 flex flex-wrap gap-2">{accounts.map(([label,value])=><button key={value} className={`rounded-lg border px-3 py-2 ${username===value?'bg-navy-800 text-white':''}`} onClick={()=>setUsername(value)}>{label}</button>)}</div><label className="mt-4 block text-sm">Demo password<input aria-label="Demo password" type="password" className="mt-1 block w-full max-w-sm rounded border p-2" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="mt-4 rounded bg-teal-500 px-4 py-2 font-semibold text-white" onClick={()=>void login()}>{busy==='login'?'Signing in…':'Login'}</button>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}</section>
 return <section className="mt-8 rounded-2xl border bg-white p-7 shadow-panel"><div className="flex justify-between"><div><p className="text-xs font-semibold text-teal-500">{user.role}</p><h2 className="text-2xl font-semibold">Investigation Setup</h2><p className="text-sm text-slate-600">{user.assigned_station||'Broader scope'} · {user.assigned_district}</p></div><button onClick={()=>void logout()}>Logout</button></div>
 {!investigation?<div className="mt-5 grid gap-4"><label>Title<input aria-label="Investigation title" className="block w-full rounded border p-2" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Purpose<select aria-label="Purpose" className="block w-full rounded border p-2" value={purpose} onChange={e=>setPurpose(e.target.value)}>{purposes.map(p=><option key={p}>{p}</option>)}</select></label><fieldset><legend>Sources</legend>{sources.map(s=><label key={s.id} className="mr-4 inline-flex gap-2"><input type="checkbox" disabled={!s.selectable} checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(x=>x!==s.id))}/>{s.name} ({s.status})</label>)}</fieldset><button className="rounded bg-navy-800 px-4 py-2 text-white" onClick={()=>void create()}>{busy==='create'?'Creating…':'Create investigation'}</button></div>:
 <div className="mt-6"><h3 className="font-semibold">Query Workspace</h3><div className="mt-2 flex flex-wrap gap-2">{investigation.selected_sources.map(s=><span key={s} className="rounded-full border px-2 py-1 text-xs">{s}</span>)}</div><textarea aria-label="Multilingual query" className="mt-3 min-h-24 w-full rounded border p-3" value={query} onChange={e=>setQuery(e.target.value)} placeholder="English, ಕನ್ನಡ, or code-mixed query"/><button className="mt-2 rounded bg-navy-800 px-4 py-2 text-white" onClick={()=>void parse()}>{busy==='preview'?'Previewing…':'Preview query'}</button>
 {preview&&<div className="mt-5 rounded border p-4"><h4 className="font-semibold">Query Preview</h4>{preview.normalised_interpretation.requires_confirmation&&<p className="text-amber-700">Confirmation required: {preview.normalised_interpretation.uncertain_fields.join(', ')}</p>}<div className="grid gap-3 sm:grid-cols-2"><label>Intent<input aria-label="Preview intent" className="block w-full rounded border p-2" value={preview.normalised_interpretation.intent} onChange={e=>setPreview({...preview,normalised_interpretation:{...preview.normalised_interpretation,intent:e.target.value}})}/></label>{['offence','location','date_from','date_to','status','case_identifier','phone','imei','vehicle_registration'].map(field=><label key={field} className="capitalize">{field.replaceAll('_',' ')}<input aria-label={`Preview ${field}`} className="block w-full rounded border p-2" value={preview.normalised_interpretation.filters[field]??''} onChange={e=>setPreview({...preview,normalised_interpretation:{...preview.normalised_interpretation,filters:{...preview.normalised_interpretation.filters,[field]:e.target.value||null}}})}/></label>)}</div><p className="mt-3 text-xs text-slate-500">Protected identifiers: {preview.normalised_interpretation.protected_tokens.join(', ')||'None'}</p><button className="mt-3 rounded bg-teal-500 px-4 py-2 text-white" onClick={()=>void run()}>{busy==='search'?'Searching…':'Confirm and run SEARCH'}</button></div>}
 {results.length>0&&<div className="mt-5"><h4 className="font-semibold">SEARCH Results ({results.length})</h4>{results.map(r=><article key={r.id} className="mt-2 rounded border p-3"><strong>{r.fir_number}</strong><p>{r.offence} · {r.status}</p><p className="text-xs">{r.jurisdiction_state} · {r.masking.applied?'Masked':'Full permitted detail'}</p><p className="text-xs">Reason: {r.match_reasons?.join(', ')||'bounded search'}</p><p className="text-xs">Source: {r.source_record_references.join(', ')}</p></article>)}</div>}<p className="mt-5 text-xs text-slate-500">Query history is stored for this investigation; advanced conversational context arrives in M4.</p></div>}
 {error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}</section>
}
