import {useEffect,useState} from 'react'
import {m3Api} from '../../api/m3'

const sections=['Cover','Investigation Summary','Purpose and Scope','Selected Sources','FIR Search Criteria','Retrieved FIR Cases','FIR Header and Incident Summary','People and Roles','Acts and Sections','Classification','FIR Organisation and Court','Arrest and Surrender Timeline','Chargesheet and Final Report','Evidence','Timeline','Related Cases and Matching Reasons','FIR Relationship Graph','FIR Record Assurance','Sources and Provenance','Source Limitations','Jurisdiction and Masking Notes','Audit Reference','Reviewer Notes','Disclaimer']
const legacySections=['Search Criteria','Retrieved Cases','Candidate Relationships','Case DNA Comparisons','Evidence Graph Summary','Record Assurance Findings','Hypothesis Challenge','Action Impact Preview','VERIFY Findings','Provenance','Data Quality','Provenance Appendix']

export function ReportConsole(){
 const [title,setTitle]=useState('ANVAYA investigation report'),[iid,setIid]=useState(''),[notes,setNotes]=useState(''),[picked,setPicked]=useState(sections),[report,setReport]=useState<any>(null),[preview,setPreview]=useState(''),[review,setReview]=useState(''),[comment,setComment]=useState(''),[events,setEvents]=useState<any[]>([]),[health,setHealth]=useState<any>(null),[reports,setReports]=useState<any[]>([]),[reviewers,setReviewers]=useState<any[]>([]),[reviewer,setReviewer]=useState(''),[meta,setMeta]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState('')
 const act=async(label:string,fn:()=>Promise<any>)=>{setBusy(label);setError('');try{return await fn()}catch(e){setError((e as Error).message);return null}finally{setBusy('')}}
 const save=async()=>{const x=await act('save',()=>report?m3Api.updateReport(report.report_id,{title,sections:picked,notes}):m3Api.createReport({title,investigation_id:iid,sections:picked,notes}));if(x)setReport({...report,...x})}
 const [detail,setDetail]=useState<any>(null),[offset,setOffset]=useState(0),[auditFilters,setAuditFilters]=useState({actor_role:'',investigation:'',report:'',event_type:'',outcome:'',request_id:'',start:'',end:''}),[user,setUser]=useState<any>(null),[view,setView]=useState('builder'),[sessionState,setSessionState]=useState('loading')
 useEffect(()=>{void m3Api.session().then(x=>{setUser(x);setSessionState('active')}).catch(()=>setSessionState('expired'))},[])
 const open=async(id:string)=>{const x=await act('detail',()=>m3Api.reportDetail(id));if(x){setDetail(x);setReport({...x.report,report_id:id})}}
 const loadAudit=(nextOffset=offset)=>{const q=new URLSearchParams({limit:'25',offset:String(nextOffset),...Object.fromEntries(Object.entries(auditFilters).filter(([,v])=>v))});void act('audit',()=>m3Api.audit(q.toString())).then(x=>x&&setEvents(x.events))}
 const decisionNeedsComment=['REJECTED','CHANGES_REQUESTED'].includes(review)
 const supervisor=user?.role==='SUPERVISOR';const visible=supervisor?['review','preview','audit','health']:['builder','preview','audit','health']
 if(sessionState==='expired')return <section className="mt-6 rounded-2xl border bg-white p-6" role="alert">Session expired or revoked. Return to the safe login state to continue.</section>
 return <section className="mt-6 rounded-2xl border bg-white p-6" aria-label="Reports">
  <nav className="mb-4 flex flex-wrap gap-2 border-b border-slate-200 pb-3" aria-label="Report navigation">{visible.map(item=><button key={item} className={view===item?'rounded-lg bg-navy-800 px-3 py-1.5 text-sm font-medium text-white shadow-sm':'rounded-lg border border-slate-200 px-3 py-1.5 text-sm text-slate-600 transition hover:border-teal-400 hover:bg-teal-50 hover:text-teal-800'} onClick={()=>setView(item)} aria-current={view===item?'page':undefined}>{item==='review'?'Supervisor Review':item==='builder'?'Reports':item==='audit'?'Audit Dashboard':item==='preview'?'Report Preview':'System Health'}</button>)}</nav>
  {view==='review'&&!supervisor&&<p role="alert">Permission denied.</p>}
  {view==='builder'&&<><h2 className="text-xl font-semibold">FIR Report Composer</h2><p className="text-sm text-slate-600">Select dataset-focused, factual sections. Preview before submission; submitted versions remain immutable.</p>
  <div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void act('reports',m3Api.reports).then(x=>x&&setReports(x.reports))}>Load reports / assigned queue</button><button onClick={()=>void act('reviewers',m3Api.reviewers).then(x=>x&&setReviewers(x))}>Load eligible reviewers</button></div>
  {reports.length===0?<p className="mt-2 text-sm text-slate-500">No loaded reports or assigned review queue items.</p>:<div>{reports.map(x=><button className="m-1 rounded border p-2" key={x.id} onClick={()=>void open(x.id)}>{x.title} · {x.status}</button>)}</div>}
  <label className="mt-3 block">Report title<input className="ml-2 border" value={title} onChange={e=>setTitle(e.target.value)}/></label>
  <label className="mt-2 block">Investigation ID<input aria-label="Investigation ID" className="ml-2 border" value={iid} onChange={e=>setIid(e.target.value)}/></label>
  <label className="mt-2 block">Eligible reviewer<select aria-label="Eligible reviewer" value={reviewer} onChange={e=>setReviewer(e.target.value)}><option value="">Select</option>{reviewers.map(x=><option key={x.username}>{x.username}</option>)}</select></label>
  <fieldset className="mt-3"><legend>Primary FIR report sections</legend>{sections.map(s=><label className="mr-2" key={s}><input type="checkbox" checked={picked.includes(s)} onChange={e=>setPicked(e.target.checked?[...picked,s]:picked.filter(x=>x!==s))}/>{s}</label>)}</fieldset><details className="mt-2"><summary className="cursor-pointer text-sm">Legacy Compatibility Sections</summary>{legacySections.map(s=><label className="mr-2 text-xs" key={s}><input type="checkbox" checked={picked.includes(s)} onChange={e=>setPicked(e.target.checked?[...picked,s]:picked.filter(x=>x!==s))}/>{s}</label>)}</details>
  <label className="mt-3 block">Investigator notes<textarea aria-label="Investigator notes" className="block w-full border" value={notes} onChange={e=>setNotes(e.target.value)}/></label>
  <div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void save()}>{busy==='save'?'Saving…':'Save draft'}</button><button disabled={!report||!reviewer} onClick={()=>void act('assign',()=>m3Api.assignReviewer(report.report_id,reviewer))}>Assign reviewer</button><button disabled={!report} onClick={()=>void act('preview',()=>m3Api.reportPreview(report.report_id)).then(x=>x&&setPreview(x.html))}>Preview</button><button disabled={!report} onClick={()=>void act('metadata',()=>m3Api.previewMetadata(report.report_id)).then(setMeta)}>Preview metadata</button><button disabled={!report} onClick={()=>void act('submit',()=>m3Api.submitReport(report.report_id)).then(x=>x&&setReport({...report,...x}))}>Submit</button></div>
  {report&&<p className="mt-2">Status: {report.status} · {report.report_id}</p>}
  {detail&&<section className="mt-3 rounded border p-3"><h3>Version and Review History</h3><p>Assigned reviewer: {detail.report.assigned_reviewer_id||'Not assigned'}</p><p>Allowed actions: {(detail.allowed_actions||[]).join(', ')}</p><ul>{(detail.versions||[]).map((v:any)=><li key={v.id}>Version {v.version_number} · {v.status} · {v.immutable?'immutable':'editable'}</li>)}</ul><ul>{(detail.review_history||[]).map((h:any,i:number)=><li key={i}>{h.username} · {h.decision} · {h.note} · {h.created_at}</li>)}</ul>{detail.report.status==='CHANGES_REQUESTED'&&<button onClick={()=>void act('version',()=>m3Api.newReportVersion(report.report_id)).then(x=>x&&setReport({...report,...x}))}>Create new editable version</button>}</section>}
  {meta&&<section className="mt-3 rounded border p-3"><h3>Report Preview Metadata</h3><p>{meta.filename} · native PDF unavailable; browser print-to-PDF available.</p><pre className="overflow-auto text-xs">{JSON.stringify(meta,null,2)}</pre></section>}
  {preview&&<section className="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-slate-50 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 bg-white px-4 py-3"><div><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-teal-700">Document preview</p><p className="text-sm text-slate-600">Use your browser’s <b>Print → Save as PDF</b>. Native PDF generation is unavailable.</p></div><button className="rounded-lg bg-navy-800 px-3 py-1.5 text-sm font-medium text-white shadow-sm hover:bg-navy-700" onClick={()=>window.print()}>Print report</button></div>
  <div className="flex flex-wrap items-center gap-2 border-b border-slate-200 bg-teal-50/60 px-4 py-2"><span className="inline-flex items-center gap-1 text-xs font-bold uppercase tracking-wide text-teal-800"><span aria-hidden>🔗</span>Cited sources</span>{picked.filter(s=>/source|provenance|citation|criteria|retrieved|audit/i.test(s)).map(s=><span key={s} className="rounded-full border border-teal-200 bg-white px-2 py-0.5 text-xs text-teal-800">{s}</span>)}<span className="ml-auto text-[11px] text-slate-500">Every claim links to a synthetic source record — no source, no factual claim.</span></div>
  <iframe title="Authenticated report preview" className="mx-auto mt-4 mb-4 block h-96 w-[92%] rounded-lg border border-slate-200 bg-white shadow-panel" srcDoc={preview}/></section>}</>}
  {view==='review'&&<><h3>Supervisor Review</h3><label>Decision<select value={review} onChange={e=>setReview(e.target.value)}><option value="">Select</option><option>APPROVED</option><option>CHANGES_REQUESTED</option><option>REJECTED</option></select></label><input aria-label="Reviewer comment" required={decisionNeedsComment} placeholder={decisionNeedsComment?'Comment required':''} value={comment} onChange={e=>setComment(e.target.value)}/><button disabled={!report||!review||(decisionNeedsComment&&!comment.trim())} onClick={()=>void act('review',()=>m3Api.reviewReport(report.report_id,{decision:review,note:comment}))}>Submit review</button></>}
  {view==='audit'&&<><h3>Audit Dashboard</h3><div className="grid gap-2 sm:grid-cols-2">{Object.entries(auditFilters).map(([key,value])=><label key={key}>{key.replaceAll('_',' ')}<input aria-label={`Audit ${key}`} type={key==='start'||key==='end'?'datetime-local':'text'} value={value} onChange={e=>setAuditFilters({...auditFilters,[key]:e.target.value})}/></label>)}</div><button onClick={()=>{setOffset(0);loadAudit(0)}}>{busy==='audit'?'Loading…':'Apply filters'}</button><button onClick={()=>{setAuditFilters({actor_role:'',investigation:'',report:'',event_type:'',outcome:'',request_id:'',start:'',end:''});setOffset(0);setEvents([])}}>Clear filters</button><p>Offset: {offset}</p><button disabled={offset===0||busy==='audit'} onClick={()=>{const n=Math.max(0,offset-25);setOffset(n);loadAudit(n)}}>Previous</button><button disabled={busy==='audit'} onClick={()=>{const n=offset+25;setOffset(n);loadAudit(n)}}>Next</button>{events.length===0?<p>Empty audit page.</p>:events.map(e=><p key={e.id}>{e.occurred_at} · {e.event_type} · {e.outcome} · {e.safe_metadata_json}</p>)}</>}
  {view==='health'&&<section className="mt-4 rounded border p-3" aria-label="System Health"><div className="flex gap-2"><h3>System Health</h3><button disabled={busy==='health'} onClick={()=>void act('health',m3Api.systemHealth).then(setHealth)}>{busy==='health'?'Checking…':'Check health'}</button></div>{!health&&busy!=='health'&&<p className="text-sm text-slate-500">Authenticated detailed health is not loaded.</p>}{health&&<div className="mt-2 text-sm"><p>Backend: {health.backend||health.status||'Unavailable'}</p><p>Database: {health.database||'Unavailable'}</p><p>Migration version: {health.migration_version??'Unavailable'}</p><p>Frontend build: M6 local build</p><p>Optional AI: {health.optional_ai||'disabled'}</p><p>Report export: {health.report_export||'browser print-to-PDF'}</p><p>Mode: {health.degraded_mode?'Degraded — available sources continue with limitations.':'Healthy'}</p><h4 className="mt-2">Source freshness</h4><ul>{(health.sources||[]).map((s:any)=><li key={s.id}>{s.name||s.id}: {s.status}</li>)}</ul>{(health.sources||[]).filter((s:any)=>s.status==='Unavailable').length>0&&<p>Unavailable sources are shown above and are not substituted as evidence.</p>}{health.degraded_mode&&<p>Safe warning: stale or unavailable sources are disclosed in downstream results and reports.</p>}</div>}</section>}{error&&<p role="alert">{error.includes('SESSION')?'Session expired. Please sign in again.':error.includes('denied')||error.includes('DENIED')?'Permission denied.':error}</p>}
 </section>
}
