import {useEffect,useState} from 'react'
import {m3Api,type User} from '../../api/m3'
import {nexusApi} from '../../api/nexus'

const roles=[['Investigator','investigator.demo'],['Crime Analyst','analyst.demo'],['Supervisor','supervisor.demo']] as const
const empty={q:'',crime_no:'',person_name:'',role:'',act:'',section:'',status:'',category:'',gravity:'',major_head:'',minor_head:''}
export function NexusWorkspace(){
 const [user,setUser]=useState<User|null>(null),[password,setPassword]=useState(''),[username,setUsername]=useState('investigator.demo'),[filters,setFilters]=useState(empty),[cases,setCases]=useState<any[]>([]),[current,setCurrent]=useState<any>(null),[brief,setBrief]=useState<any>(null),[related,setRelated]=useState<any[]>([]),[identities,setIdentities]=useState<any[]>([]),[assurance,setAssurance]=useState<any[]>([]),[graph,setGraph]=useState<any>(null),[report,setReport]=useState<any>(null),[readiness,setReadiness]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState('')
 const run=async(label:string,fn:()=>Promise<any>)=>{setBusy(label);setError('');try{return await fn()}catch(e){setError((e as Error).message);return null}finally{setBusy('')}}
 useEffect(()=>{if(user)void run('readiness',nexusApi.readiness).then(setReadiness)},[user])
 const login=async()=>{const result=await run('login',()=>m3Api.login(username,password));if(result)setUser(result)}
 const search=async()=>{const result=await run('search',()=>nexusApi.search(filters));if(result){setCases(result.results);setCurrent(null);setBrief(null)}}
 const open=async(id:string)=>{const result=await run('case',()=>nexusApi.case360(id));if(result){setCurrent(result);setBrief(null);setRelated([]);setIdentities([]);setAssurance([]);setGraph(null)}}
 const loadInsight=async(kind:'brief'|'related'|'identities'|'assurance'|'graph'|'report')=>{if(!current)return;const map={brief:nexusApi.brief,related:nexusApi.related,identities:nexusApi.identities,assurance:nexusApi.assurance,graph:nexusApi.graph,report:nexusApi.reportPreview};const result=await run(kind,()=>map[kind](current.case.id));if(!result)return;if(kind==='brief')setBrief(result);if(kind==='related')setRelated(result.results);if(kind==='identities')setIdentities(result.suggestions);if(kind==='assurance')setAssurance(result.findings);if(kind==='graph')setGraph(result);if(kind==='report')setReport(result)}
 const review=async(item:any,decision:string)=>{if(!current)return;const result=await run('identity',()=>nexusApi.reviewIdentity(current.case.id,{related_case_id:item.right_case_id===current.case.id?item.left_case_id:item.right_case_id,person_id:item.shared_person_id,decision,note:'Synthetic demo human review'}));if(result)await loadInsight('identities')}
 if(!user)return <section className="mt-8 rounded-2xl border bg-white p-7 shadow-panel"><h2 className="text-2xl font-semibold">ANVAYA NEXUS secure demo</h2><p className="mt-1 text-sm text-slate-600">Synthetic FIR data only. Roles, jurisdiction and audit controls are enforced on the server.</p><div className="mt-4 flex flex-wrap gap-2">{roles.map(([label,value])=><button className="rounded border px-3 py-2" key={value} onClick={()=>setUsername(value)}>{label}</button>)}</div><label className="mt-4 block text-sm">Demo password<input aria-label="Demo password" className="ml-2 rounded border p-2" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="mt-3 rounded bg-navy-800 px-4 py-2 text-white" onClick={()=>void login()}>{busy==='login'?'Signing in…':'Sign in'}</button>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}</section>
 return <section className="mt-8 grid gap-5" aria-label="ANVAYA NEXUS workspace"><header className="rounded-2xl bg-navy-950 p-6 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-teal-300">{user.role}</p><h2 className="mt-1 text-2xl font-semibold">FIR intelligence workspace</h2><p className="mt-1 text-sm text-slate-300">Search → understand → verify → report, with factual evidence and human control.</p></div><button className="rounded border border-slate-500 px-3 py-1 text-sm" onClick={()=>void m3Api.logout().then(()=>setUser(null))}>Logout</button></div>{readiness&&<p className="mt-4 text-xs text-teal-200">Synthetic FIR domain: {readiness.counts.fir_case_details} case fixtures · schema v{readiness.schema_version}</p>}</header>
 <section className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Evidence-led FIR search</h3><p className="mt-1 text-sm text-slate-600">Search the synthetic benchmark by any supported record field. Results are source-backed, role-filtered, and never infer guilt, risk, or identity.</p><label className="mt-4 block text-sm font-medium">Find across record fields<input aria-label="Find across record fields" placeholder="e.g. Kavya, cyber, 66D, transferred, Central" className="mt-1 block w-full rounded border p-2" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/></label><div className="mt-4 grid gap-3 md:grid-cols-3">{[['crime_no','Crime number'],['person_name','Person name'],['act','Act'],['section','Section'],['status','Status'],['category','Case category'],['gravity','Gravity'],['major_head','Major crime head'],['minor_head','Minor crime head']].map(([key,label])=><label className="text-sm" key={key}>{label}<input className="mt-1 block w-full rounded border p-2" value={filters[key as keyof typeof filters]} onChange={e=>setFilters({...filters,[key]:e.target.value})}/></label>)}<label className="text-sm">Person role<select className="mt-1 block w-full rounded border p-2" value={filters.role} onChange={e=>setFilters({...filters,role:e.target.value})}><option value="">Any role</option><option>COMPLAINANT</option><option>VICTIM</option><option>ACCUSED</option></select></label></div><div className="mt-4 flex flex-wrap gap-2"><button className="rounded bg-teal-600 px-4 py-2 text-white" onClick={()=>void search()}>{busy==='search'?'Searching…':'Search FIR records'}</button><button className="rounded border px-4 py-2" onClick={()=>{setFilters(empty);setCases([]);setCurrent(null)}}>Clear</button></div><div className="mt-4 grid gap-3">{cases.map(item=><button className="rounded border p-4 text-left hover:border-teal-600" key={item.id} onClick={()=>void open(item.id)}><b>{item.crime_number}</b> · {item.offence} · {item.status}<p className="mt-1 text-sm text-slate-600">{item.case_category_code} · {item.crime_major_head} · {item.station_name || item.station_id}{item.court_name ? ` · ${item.court_name}` : ''}</p><p className="mt-1 text-xs text-slate-500">{item.brief_facts}</p></button>)}{cases.length===0&&<p className="text-sm text-slate-500">Run a search to view synthetic FIR records.</p>}</div></section>
 {current&&<><section className="rounded-2xl border bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-semibold">Case 360 · {current.case.crime_number}</h3><p className="text-sm text-slate-600">{current.case.unit_name} · {current.case.status} · {current.case.offence}</p></div><div className="flex flex-wrap gap-2">{(['brief','related','identities','assurance','graph','report'] as const).map(kind=><button className="rounded border px-3 py-2 text-sm" key={kind} onClick={()=>void loadInsight(kind)}>Load {kind==='brief'?'Brief':kind==='report'?'report draft':kind}</button>)}</div></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Info title="People" value={current.people.map((p:any)=>`${p.role_type}: ${p.display_name}`).join('\n')||'None'}/><Info title="Legal sections" value={current.legal_sections.map((x:any)=>`${x.act_code} § ${x.section_code}`).join('\n')||'None'}/><Info title="Arrest / surrender" value={current.arrest_surrender_events.map((x:any)=>`${x.event_type}: ${x.accused_name}`).join('\n')||'None'}/><Info title="Provenance" value={current.provenance.source_record_id}/></div></section>
 {brief&&<section className="rounded-2xl border border-teal-200 bg-teal-50 p-6"><h3 className="font-semibold">Evidence-Grounded Investigation Brief</h3><ul className="mt-3 space-y-3 text-sm">{brief.statements.map((s:any,i:number)=><li key={i}>{s.statement}<p className="mt-1 text-xs text-slate-500">Sources: {s.source_references.join(', ')}</p></li>)}</ul><p className="mt-4 text-xs text-slate-600">{brief.limitations.join(' ')}</p></section>}
 {related.length>0&&<section className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Related cases: evidence and counter-evidence</h3>{related.map(item=><article className="mt-3 rounded border p-3" key={item.case_id}><b>{item.crime_number}</b> · {item.relationship_tier}<p className="text-sm">{item.reason}</p><p className="mt-1 text-xs text-teal-700">Evidence: {item.supporting_evidence.join(', ')}</p><p className="mt-1 text-xs text-amber-800">Counter-evidence: {item.counter_evidence.join(' ')}</p></article>)}</section>}
 {identities.length>0&&<section className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Explainable identity link suggestions</h3><p className="text-sm text-slate-600">Suggestions never merge records automatically.</p>{identities.map(item=><article className="mt-3 rounded border p-3" key={item.id}><b>{item.person_display_name}</b> · {item.status}<p className="text-sm">Match: {item.matches.join(', ')}</p><p className="text-xs text-amber-800">Conflict / limitation: {item.conflicts.join(' ')}</p><div className="mt-2 flex gap-2"><button className="rounded border px-2 py-1 text-sm" onClick={()=>void review(item,'CONFIRMED')}>Confirm review</button><button className="rounded border px-2 py-1 text-sm" onClick={()=>void review(item,'REJECTED')}>Reject</button><button className="rounded border px-2 py-1 text-sm" onClick={()=>void review(item,'NEEDS_REVIEW')}>Need review</button></div></article>)}</section>}
 {assurance.length>0&&<section className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Contradiction and timeline radar</h3>{assurance.map((item:any)=><p className="mt-2 rounded bg-slate-50 p-3 text-sm" key={item.rule_id}><b>{item.severity}</b> · {item.message}<span className="ml-2 text-xs text-slate-500">{item.source_references.join(', ')}</span></p>)}</section>}
 {graph&&<section className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Factual relationship graph</h3><p className="mt-2 text-sm text-slate-600">{graph.warning}</p><div className="mt-3 grid gap-2 text-sm">{graph.edges.map((e:any,i:number)=><p className="rounded bg-slate-50 p-2" key={i}>{e.from} — {e.type} → {e.to} <span className="text-xs text-slate-500">{e.source_record_reference}</span></p>)}</div></section>}
 {report&&<section className="rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><h3 className="font-semibold">Source-cited report draft</h3><button className="rounded border px-3 py-1 text-sm" onClick={()=>window.print()}>Print to PDF</button></div><iframe title="Source-cited report draft" className="mt-3 h-96 w-full rounded border" srcDoc={report.html}/></section>}</>}{error&&<p role="alert" className="text-red-700">{error}</p>}</section>
}
function Info({title,value}:{title:string;value:string}){return <div className="rounded bg-slate-50 p-3"><h4 className="text-sm font-semibold">{title}</h4><p className="mt-1 whitespace-pre-line text-sm text-slate-700">{value}</p></div>}
