from __future__ import annotations

from typing import Any, Protocol

from backend.anvaya.platform.capabilities import Capability


class RepositoryBackend(Protocol):
    backend_name: str

    def health_check(self) -> str: ...
    def transaction_capability(self) -> Capability: ...
    def schema_version_capability(self) -> Capability: ...
    def close(self) -> None: ...


class AuthenticationBackend(Protocol):
    backend_name: str

    def resolve_identity(self, token: str | None, request_id: str | None = None) -> Any: ...
    def login_session(self, username: str, password: str, ttl_minutes: int, request_id: str) -> tuple[str, Any]: ...
    def revoke_session(self, token: str | None, request_id: str) -> None: ...
    def capability(self) -> Capability: ...


class ArtifactStorageBackend(Protocol):
    backend_name: str

    def store_report_html(self, artifact_id: str, html: str) -> str: ...
    def retrieve_artifact(self, artifact_id: str) -> str: ...
    def delete_artifact(self, artifact_id: str) -> None: ...
    def capability(self) -> Capability: ...


class SchemaBootstrapBackend(Protocol):
    backend_name: str

    def inspect_schema_state(self) -> dict[str, Any]: ...
    def bootstrap(self) -> None: ...
    def seed_synthetic_demo_data(self) -> None: ...
    def capability(self) -> Capability: ...
