import {render,screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {AuthQueryWorkspace} from '../features/m3/AuthQueryWorkspace'

const user={id:'SYN-USR-INV',username:'investigator.demo',role:'INVESTIGATOR',assigned_station:'SYN-STN-01',assigned_district:'SYN-DST-01'}
const sources=[{id:'CCTNS_REPLICA',name:'Synthetic CCTNS',status:'Fresh',selectable:true},{id:'COURT_REPLICA',name:'Court P1',status:'Unavailable',selectable:false}]
const inv={id:'SYN-INV-1',title:'Synthetic investigation',purpose:'Active Case Investigation',selected_sources:['CCTNS_REPLICA'],assigned_station:'SYN-STN-01',assigned_district:'SYN-DST-01'}
const preview={message_id:'SYN-MSG-1',normalised_interpretation:{intent:'SEARCH',filters:{offence:null,location:null},selected_sources:['CCTNS_REPLICA'],result_limit:25,confidence:.6,uncertain_fields:['offence','location'],protected_tokens:[],requires_confirmation:true}}
const result={results:[{id:'SYN-CASE-1',fir_number:'SYN-FIR-1',offence:'CHAIN_SNATCHING',status:'UNRESOLVED',jurisdiction_state:'external',masking:{applied:true,level:'EXTERNAL',fields:['phone']},source_record_references:['SYN-SR-1']}],result_count:1}
const envelope=(data:unknown,status=200)=>new Response(JSON.stringify({request_id:'r',warnings:[],data}),{status,headers:{'Content-Type':'application/json'}})
function mockApi(options?:{deny?:boolean}){return vi.spyOn(globalThis,'fetch').mockImplementation(async input=>{const url=String(input);if(url.includes('/auth/login'))return envelope(user);if(url.includes('/auth/logout'))return envelope({logged_out:true});if(url.includes('/m3/sources'))return envelope(sources);if(url==='/api/investigations'&&options?.deny)return new Response(JSON.stringify({message:'Purpose denied'}),{status:403});if(url==='/api/investigations')return envelope(inv,201);if(url.includes('/query/preview'))return envelope(preview);if(url.includes('/search'))return envelope(result);throw new Error(`Unexpected ${url}`)})}
async function signedIn(){mockApi();render(<AuthQueryWorkspace/>);await userEvent.type(screen.getByLabelText('Demo password'),'demo');await userEvent.click(screen.getByRole('button',{name:'Login'}));return screen.findByText('INVESTIGATOR')}

it('renders demo roles and synthetic login explanation',()=>{render(<AuthQueryWorkspace/>);expect(screen.getByRole('heading',{name:'Demo Login'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Crime Analyst'})).toBeInTheDocument();expect(screen.getByText(/Synthetic roles only/)).toBeInTheDocument()})
it('supports successful role login and logout',async()=>{await signedIn();expect(screen.getByText('INVESTIGATOR')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Logout'}));expect(await screen.findByRole('heading',{name:'Demo Login'})).toBeInTheDocument()})
it('supports purpose/source selection and disables unavailable source',async()=>{await signedIn();expect(screen.getByLabelText('Purpose')).toHaveValue('Active Case Investigation');expect(screen.getByLabelText(/Court P1/)).toBeDisabled();expect(screen.getByLabelText(/Synthetic CCTNS/)).toBeChecked()})
it('previews ambiguity, allows intent editing and renders masked SEARCH result',async()=>{await signedIn();await userEvent.click(screen.getByRole('button',{name:'Create investigation'}));await userEvent.type(await screen.findByLabelText('Multilingual query'),'show maadi records');await userEvent.click(screen.getByRole('button',{name:'Preview query'}));expect(await screen.findByText(/Confirmation required/)).toBeInTheDocument();const intent=screen.getByLabelText('Preview intent');await userEvent.clear(intent);await userEvent.type(intent,'SEARCH');await userEvent.click(screen.getByRole('button',{name:'Confirm and run SEARCH'}));expect(await screen.findByText(/SEARCH Results/)).toBeInTheDocument();expect(screen.getByText(/Masked/)).toBeInTheDocument();expect(screen.getByText(/SYN-SR-1/)).toBeInTheDocument()})
it('shows denial/error state',async()=>{mockApi({deny:true});render(<AuthQueryWorkspace/>);await userEvent.type(screen.getByLabelText('Demo password'),'demo');await userEvent.click(screen.getByRole('button',{name:'Login'}));await screen.findByText('INVESTIGATOR');await userEvent.click(screen.getByRole('button',{name:'Create investigation'}));expect(await screen.findByRole('alert')).toHaveTextContent('Purpose denied')})
