import {render,screen,within} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {vi,it,expect} from 'vitest'
import {ReportConsole} from '../features/m6/ReportConsole'

const envelope=(data:unknown,status=200)=>new Response(JSON.stringify({request_id:'m6-test',warnings:[],data}),{status,headers:{'Content-Type':'application/json'}})
function mock(role='INVESTIGATOR'){vi.spyOn(globalThis,'fetch').mockImplementation(async input=>{const url=String(input);if(url.includes('/auth/session'))return envelope({id:'SYN-USR',role});if(url==='/api/reports')return envelope({reports:[]});if(url==='/api/reviewers')return envelope([{username:'supervisor.demo',role:'SUPERVISOR'}]);if(url.includes('/audit-events'))return envelope({events:[],limit:25,offset:0});if(url==='/api/system-health')return envelope({backend:'ok',database:'ok',migration_version:4,sources:[{id:'CCTNS_REPLICA',status:'Fresh'},{id:'COURT_REPLICA',status:'Unavailable'}],optional_ai:'disabled',report_export:'browser-print-to-PDF',degraded_mode:true});return envelope({})})}
it('renders role-aware report navigation, structured audit fields, health and watermark-safe states',async()=>{mock();const {container}=render(<ReportConsole/>);const scope=within(container);expect(await scope.findByRole('navigation',{name:'Report navigation'})).toBeInTheDocument();expect(scope.getByRole('button',{name:'Reports'})).toBeInTheDocument();expect(scope.queryByRole('button',{name:'Supervisor Review'})).not.toBeInTheDocument();await userEvent.click(scope.getByRole('button',{name:'Audit Dashboard'}));await scope.findByRole('heading',{name:'Audit Dashboard'});for(const field of ['actor_role','investigation','report','event_type','outcome','request_id','start','end'])expect(scope.getByLabelText(`Audit ${field}`)).toBeInTheDocument();expect(scope.getByRole('button',{name:'Previous'})).toBeDisabled();await userEvent.click(scope.getByRole('button',{name:'System Health'}));await userEvent.click(scope.getByRole('button',{name:'Check health'}));expect(await scope.findByText(/Migration version: 4/)).toBeInTheDocument();expect(scope.getByText(/COURT_REPLICA: Unavailable/)).toBeInTheDocument()})
it('shows supervisor review navigation for a supervisor session',async()=>{mock('SUPERVISOR');render(<ReportConsole/>);expect(await screen.findByRole('button',{name:'Supervisor Review'})).toBeInTheDocument()})
