import { useEffect, useState, useCallback } from 'react'
import { m3Api } from '../../api/m3'
import { useAuthStore } from '../../stores/authStore'
import { useLocale } from '../../i18n/portal'

const statusColors: Record<string, string> = {
  DRAFT: 'bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-300',
  SUBMITTED: 'bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
  UNDER_REVIEW: 'bg-amber-50 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400',
  APPROVED: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400',
  REJECTED: 'bg-red-50 text-red-700 dark:bg-red-900/30 dark:text-red-400',
}

export function ReportsView() {
  const user = useAuthStore((s) => s.user)
  const { locale } = useLocale()
  const [reports, setReports] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [isModalOpen, setIsModalOpen] = useState(false)
  const [submitting, setSubmitting] = useState(false)

  // New report form state
  const [newTitle, setNewTitle] = useState('')
  const [newNotes, setNewNotes] = useState('')

  const load = useCallback(async () => {
    setLoading(true)
    setError('')
    try {
      const data = await m3Api.reports()
      const list = Array.isArray(data?.reports) ? data.reports : (Array.isArray(data) ? data : [])
      setReports(list)
    } catch (e) {
      setError((e as Error).message || 'Unable to load reports.')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { void load() }, [load])

  const handleCreateReport = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!newTitle.trim()) return
    setSubmitting(true)
    try {
      await m3Api.createReport({
        title: newTitle.trim(),
        notes: newNotes.trim() || 'Synthetic Investigation Brief generated by Karnataka Police Officer.',
        sections: ['Cover', 'Investigation Summary', 'Evidence', 'Disclaimer'],
        status: 'DRAFT'
      })
      setNewTitle('')
      setNewNotes('')
      setIsModalOpen(false)
      await load()
    } catch (err) {
      alert((err as Error).message || 'Failed to create report.')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="flex-1 overflow-y-auto px-6 py-6" style={{ fontFamily: "'Inter', sans-serif" }}>
      <div className="mx-auto max-w-5xl">

        {/* Header */}
        <div className="mb-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <span className="material-icons-outlined" style={{ color: '#003087', fontSize: 24 }}>description</span>
              {locale === 'kn' ? 'ತನಿಖಾ ವರದಿಗಳು' : 'Investigation Reports'}
            </h2>
            <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
              {locale === 'kn'
                ? 'ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ಹೊಸ ತನಿಖಾ ವರದಿಗಳನ್ನು ರಚಿಸಿ, ನಿರ್ವಹಿಸಿ ಮತ್ತು PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ'
                : 'Create, manage, and download official investigation briefs and dossiers anytime.'}
            </p>
          </div>

          <button
            onClick={() => setIsModalOpen(true)}
            className="flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold text-white transition-all shadow-md shrink-0"
            style={{ background: '#003087' }}
          >
            <span className="material-icons-outlined" style={{ fontSize: 18 }}>add_circle</span>
            {locale === 'kn' ? '+ ಹೊಸ ವರದಿ ರಚಿಸಿ' : '+ Create Report'}
          </button>
        </div>

        {error && (
          <div className="mb-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800 dark:border-amber-800 dark:bg-amber-900/20 dark:text-amber-300">
            ⚠️ {error} — Showing cached data.
          </div>
        )}

        {loading ? (
          <div className="space-y-3">
            {[1, 2, 3].map((i) => <div key={i} className="skeleton h-20 rounded-xl" />)}
          </div>
        ) : reports.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50/80 p-12 text-center dark:border-slate-700 dark:bg-slate-800/40">
            <div className="mx-auto mb-3 flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-[#003087] dark:bg-slate-700 dark:text-blue-400">
              <span className="material-icons-outlined" style={{ fontSize: 28 }}>post_add</span>
            </div>
            <h3 className="text-base font-bold text-slate-800 dark:text-slate-200">
              {locale === 'kn' ? 'ಇನ್ನೂ ವರದಿಗಳಿಲ್ಲ' : 'No Investigation Reports Yet'}
            </h3>
            <p className="mt-1 text-xs text-slate-500 dark:text-slate-400 max-w-md mx-auto">
              {locale === 'kn'
                ? '«+ ಹೊಸ ವರದಿ ರಚಿಸಿ» ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡುವ ಮೂಲಕ ಹೊಸ ತನಿಖಾ ವರದಿಯನ್ನು ರಚಿಸಿ.'
                : 'Click "+ Create Report" above to generate a new case report anytime. Reports are instantly downloadable as official PDFs.'}
            </p>
            <button
              onClick={() => setIsModalOpen(true)}
              className="mt-4 inline-flex items-center gap-1.5 rounded-xl px-4 py-2 text-xs font-bold text-white shadow"
              style={{ background: '#003087' }}
            >
              <span className="material-icons-outlined" style={{ fontSize: 16 }}>add</span>
              {locale === 'kn' ? 'ವರದಿ ರಚಿಸಿ' : 'Create First Report'}
            </button>
          </div>
        ) : (
          <div className="divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white dark:divide-slate-700 dark:border-slate-700 dark:bg-slate-900 shadow-sm overflow-hidden">
            {reports.map((r: any) => (
              <div key={r.id} className="flex flex-col sm:flex-row sm:items-center justify-between p-4 gap-4 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-bold text-[#003087] dark:text-blue-400">{r.id}</span>
                    <h4 className="font-bold text-slate-900 dark:text-white truncate">{r.title || 'Untitled Report'}</h4>
                  </div>
                  <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                    📅 {r.created_at ? new Date(r.created_at).toLocaleDateString() : 'Today'}
                    {r.owner_user_id ? ` · Officer: ${r.owner_user_id}` : ''}
                  </p>
                </div>
                <div className="flex items-center gap-3 shrink-0">
                  <span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusColors[r.status] || statusColors.DRAFT}`}>
                    {(r.status || 'DRAFT').replace(/_/g, ' ')}
                  </span>
                  <button
                    onClick={async () => {
                      try {
                        await m3Api.reportPdf(r.id)
                      } catch (err) {
                        alert((err as Error).message || 'Unable to download report PDF.')
                      }
                    }}
                    className="flex items-center gap-1.5 rounded-xl border border-teal-200 bg-teal-50 px-3.5 py-2 text-xs font-bold text-teal-700 hover:bg-teal-100 dark:border-teal-800 dark:bg-teal-900/40 dark:text-teal-300 transition-all shadow-sm"
                  >
                    <span className="material-icons-outlined" style={{ fontSize: 16 }}>picture_as_pdf</span>
                    {locale === 'kn' ? 'PDF ಡೌನ್‌ಲೋಡ್' : 'Download PDF'}
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Create Report Modal */}
        {isModalOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-fade-in"
            onClick={() => setIsModalOpen(false)}>
            <div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900 border border-slate-200 dark:border-slate-800 animate-scale-in"
              onClick={(e) => e.stopPropagation()}>
              <div className="flex items-center justify-between border-b pb-3 dark:border-slate-800">
                <div className="flex items-center gap-2">
                  <span className="material-icons-outlined text-[#003087] dark:text-blue-400" style={{ fontSize: 24 }}>post_add</span>
                  <h3 className="text-base font-bold text-slate-900 dark:text-white">
                    {locale === 'kn' ? 'ಹೊಸ ತನಿಖಾ ವರದಿ ರಚಿಸಿ' : 'Create Investigation Report'}
                  </h3>
                </div>
                <button onClick={() => setIsModalOpen(false)} className="rounded-lg p-1 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800">
                  <span className="material-icons-outlined" style={{ fontSize: 18 }}>close</span>
                </button>
              </div>

              <form onSubmit={handleCreateReport} className="mt-4 space-y-4">
                <div>
                  <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">
                    {locale === 'kn' ? 'ವರದಿಯ ಶೀರ್ಷಿಕೆ' : 'Report Title *'}
                  </label>
                  <input
                    type="text"
                    required
                    value={newTitle}
                    onChange={(e) => setNewTitle(e.target.value)}
                    placeholder="e.g. Investigation Brief: Theft Incident FIR-1024"
                    className="w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm outline-none focus:border-[#003087] dark:border-slate-700 dark:bg-slate-800 dark:text-white"
                  />
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">
                    {locale === 'kn' ? 'ತನಿಖಾ ಟಿಪ್ಪಣಿಗಳು / ವಿವರಗಳು' : 'Investigation Summary & Findings'}
                  </label>
                  <textarea
                    rows={4}
                    value={newNotes}
                    onChange={(e) => setNewNotes(e.target.value)}
                    placeholder="Enter summary of findings, evidence timeline, suspect details..."
                    className="w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm outline-none focus:border-[#003087] dark:border-slate-700 dark:bg-slate-800 dark:text-white"
                  />
                </div>

                <div className="flex justify-end gap-3 pt-2 border-t dark:border-slate-800">
                  <button
                    type="button"
                    onClick={() => setIsModalOpen(false)}
                    className="rounded-xl px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800"
                  >
                    {locale === 'kn' ? 'ರದ್ದುಮಾಡಿ' : 'Cancel'}
                  </button>
                  <button
                    type="submit"
                    disabled={submitting || !newTitle.trim()}
                    className="rounded-xl px-5 py-2 text-xs font-bold text-white shadow-md disabled:opacity-50"
                    style={{ background: '#003087' }}
                  >
                    {submitting ? 'Creating...' : (locale === 'kn' ? 'ವರದಿ ಸೇರಿಸಿ' : 'Create & Save Report')}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

      </div>
    </div>
  )
}
